### ISSUE TITLE
Github Docs appear unreadable

### ISSUE THREAD

**Issue by ashwinvis** [vednoc/dark-github#7]
See https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

![image](https://user-images.githubusercontent.com/9155111/131072483-6f702ecd-2b86-45ef-a157-766c91557242.png)

**Comment by ashwinvis** [comment]
This is if I keep "Default light" as my [preferred theme](https://github.com/settings/appearance). Changing to a dark theme rectifies this, but then I lose the ability to switch back to light theme instantly.

**Comment by the-j0k3r** [comment]
This is a two pronged issue as far as I was able to determine with my own style a fork from this.

1 CSS vars that the `:root:not(#z)` is not enough anymore because docs uses `[data-color-mode="light"][data-light-theme="light"]` so to override we need something else like maybe `:root:not(#z) *` in the following line

https://github.com/vednoc/dark-github/blob/f38d840ab4e7a37423f697e9d305790db33d1e9d/github.user.styl#L282

2. docs are now using some type CSS vars that change with every update, this is also been observed by myself as being spreading across sub domains and even main GitHub.

I addressed this by adding overrides to a docs subdomain (on my fork) but in this style no such overrides exist at this time.

re: dark vs light a personal word, I do recommend that light mode is best as default because any issues are more visible rather than supporting dark modes as well as light modes when using 3rd party styles like this in conjunction (i.e. together), but that also depends on the actual developers of  3rd party styles

PS
Inline styles that contain non CSS vars color properties also affect docs and GitHub in very specific areas, its like a game of wack a mole.

**Comment by vednoc** [comment]
It's been fixed in `v1.2.1`. I apologize about the delay!

@the-j0k3r I ended up using `*`, but let me know if causes conflicts and/or performance issues.

**Comment by the-j0k3r** [comment]
> `*`, but let me know if causes conflicts and/or performance issues.

I cannot, since I dont use this style eh, so that should be more for the op =)

**Comment by ashwinvis** [comment]
The sidebar is consistent but the main docs page still has dark text. Note: that I am using Github's built-in light theme in my account settings and Dark-Github opportunistically.

![image](https://user-images.githubusercontent.com/9155111/133220887-3e5f93e6-3875-42bc-b520-93a051b7539f.png)

**Comment by the-j0k3r** [comment]
the docs site needs special handling that this style doesn't have its own subdomain section for. It use to though though most of it would be useless now, but not all of it.

they have a great deal of dynamic generated classes for one and a great deal of inline styles and is hog for constant attention and fixes.

**Comment by ashwinvis** [comment]
Agreed. I think the best fix is to avoid styling `docs` altogether and drop it from the regex

https://github.com/vednoc/dark-github/blob/4031ed0609637aa8dc4713ff7b545084d10a3f1d/github.user.styl#L280

**Comment by ashwinvis** [comment]
As a workaround, I kept the dark-github userstyle as it is and resorted to writing another small userstyle for `docs.github.com`

```css
h1, h2, h3, li, .markdown-body p, summary {
	color: #ddd
}
```
